name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: "Hello"
        required: true
        description: A cheeerful world
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"